baseurl: https://dearbojack.github.io/decode
languageCode: en-us
title: Decode
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
publishDir: "docs"
footnotereturnlinkcontents: ↩
enableGitInfo: true

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/
  tags: /decode/tags/:slug/
  categories: /decode/categories/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Tags"
      url: "/tags/"
      weight: 3
    - name: "Categories"
      url: "/categories/"
      weight: 4
    - name: "Subscribe"
      url: "/index.xml"

params:
  description: "How I live my life"
  footer: "&copy; Dali Han 2023 | [Github](https://github.com/dearbojack)"
  highlightjsLang: ["javascript"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"