baseurl: https://dearbojack.github.io/decode
languageCode: en-us
title: Decode
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
publishDir: "docs"
footnotereturnlinkcontents: ↩
enableGitInfo: true

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/
  journal: /journal/:year/:month/:day/:slug/

menu:
  main:
    - name: "HOME"
      url: "/"
      weight: 1
    - name: "ABOUT"
      url: "/about/"
      weight: 2
    # let's remove all this and keep it simple
    # - name: "Tags"
    #   url: "/tags/"
    #   weight: 3
    - name: "RSS"
      url: "/index.xml"

params:
  description: "How I live my life"
  footer: "&copy; Dali Han 2023 | [Github](https://github.com/dearbojack)"
  highlightjsLang: ["javascript"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
    style: monokai
    tabWidth: 2
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
  goldmark:
    extensions:
      footnote: true
      taskList: true
      table: true
    renderer:
      unsafe: true
